export const TeamLogo = {
    '국내축구': [
        { name: '울산 HD FC', img: '/TeamLogoImages/K_LEAGUE/울산현대.png'  },
        { name: '김천상무 FC', img: '/TeamLogoImages/K_LEAGUE/김천상무.png' },
        { name: '강원 FC', img: '/TeamLogoImages/K_LEAGUE/강원FC.png' },
        { name: '포항 노틸러스', img: '/TeamLogoImages/K_LEAGUE/포항스틸러스.png' },
        { name: 'FC서울', img: '/TeamLogoImages/K_LEAGUE/FC서울.png' },
        { name: '수원FC', img: '/TeamLogoImages/' },
        { name: '제주 유나이티드', img: '/TeamLogoImages/K_LEAGUE/제주유나이티드.png' },
        { name: '대전 하나 시티즌', img: '/TeamLogoImages/K_LEAGUE/대전하나시티즌FC.png' },
        { name: '광주 FC', img: '/TeamLogoImages/K_LEAGUE/광주FC.jpg' },
        { name: '전북 현대 모터스', img: '/TeamLogoImages/K_LEAGUE/전북현대 모터스.png' },
        { name: '대구FC', img: '/TeamLogoImages/K_LEAGUE/대구FC.png' },
        { name: '인천 유나이티드', img: '/TeamLogoImages/K_LEAGUE/인천유나이티드.png' },
    ],

    '해외축구': [
        { name: '레알 마드리드', img: '/TeamLogoImages/SUPER_LEAGUE/레알마드리드.png' },
        { name: '리버풀', img: '/TeamLogoImages/SUPER_LEAGUE/리버풀.png' },
        { name: '맨체스터 시티', img: '/TeamLogoImages/SUPER_LEAGUE/맨체스터시티.png' },
        { name: '맨체스터 유나이티드', img: '/TeamLogoImages/SUPER_LEAGUE/맨유.png' },
        { name: '첼시', img: '/TeamLogoImages/SUPER_LEAGUE/첼시.png' },
        { name: '토트넘', img: '/TeamLogoImages/SUPER_LEAGUE/토트넘.png' },    
        { name: '바이에른 뮌헨', img: '/TeamLogoImages/SUPER_LEAGUE/뮌헨.png' },
        { name: '유벤투스', img: '/TeamLogoImages/SUPER_LEAGUE/유벤투스.png' },
        { name: 'AC밀란', img: '/TeamLogoImages/SUPER_LEAGUE/AC밀란.png' },
        { name: '인터 밀란', img: '/TeamLogoImages/SUPER_LEAGUE/인터밀란.png' },
        { name: 'PSG', img: '/TeamLogoImages/SUPER_LEAGUE/PSG.png' },
        { name: '알 힐랄', img: '/TeamLogoImages/SUPER_LEAGUE/알힐랄.png' },
    ],
    '국내야구': [
        { name: 'LG', img: '' },
        { name: 'KIA', img: '' },
        { name: '삼성', img: '' },
        { name: '두산', img: '' },
        { name: 'SSG', img: '' },
        { name: 'KT', img: '' },
        { name: '롯데', img: '' },
        { name: '한화', img: '' },
        { name: 'NC', img: '' },
        { name: '키움', img: '' },
    ],
    '여자배구': [
        { name: '흥국생명', img: '' },
        { name: '현대건설', img: '' },
        { name: 'IBK기업은행', img: '' },
        { name: '정관장', img: '' },
        { name: '한국도로공사', img: '' },
        { name: '페퍼저축은행', img: '' },
        { name: 'GS칼텍스', img: '' },
    ],
    'e스포츠': [
        { name: 'T1', img: '' },
        { name: '젠지', img: '' },
        { name: '한화', img: '' },
        { name: 'KT', img: '' },
        { name: '담원기아', img: '' },
        { name: '광동', img: '' },
        { name: '피어엑스', img: '' },
        { name: '농심', img: '' },
        { name: 'DRX', img: '' },
        { name: '브리온', img: '' },
    ],
};
